apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090   # container-to-container, same docker network
    isDefault: true
    editable: true
